name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt1-dev

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest coverage

      - name: Lint
        run: flake8 src tests --max-line-length=120 --statistics

      - name: Tests
        env:
          OPENAI_API_KEY: dummy
        run: |
          coverage run -m pytest -q
          coverage xml

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
